# ifndef INCLUDES_H
# define INCLUDES_H

#include <iostream>
#include <string>    
#include <utility>
#include <sstream> 
#include <algorithm> 
#include <stdio.h> 
#include <stdlib.h> 
#include <vector> 
#include <fstream> 
#include <cmath> 
#include <cstdlib>
#include <sys/stat.h>
#include <iterator>
#include <ostream>
#include <iomanip>
#include <stdexcept>
#include <limits>
#include "TROOT.h"
#include "TSystem.h"
#include "TParticle.h"
#include "TParticlePDG.h"
#include "TThread.h"
#include "TFile.h"
#include "TTree.h"
#include "TChain.h"
#include "TH1D.h"
#include "TProfile.h"
#include <TH2.h> 
#include <TF1.h> 
#include <TF2.h> 
#include <THStack.h> 
#include <TStyle.h> 
#include <TGraph.h> 
#include <TGraph2D.h> 
#include <TGraphErrors.h> 
#include <TCanvas.h> 
#include <TLegend.h> 
#include <TGaxis.h> 
#include <TString.h> 
#include <TColor.h> 
#include <TLine.h> 
#include <TExec.h> 
#include <TFitResultPtr.h> 
#include <TFitResult.h> 
#include <TLatex.h> 
#include <TMath.h>
#include <TLorentzVector.h>
#include <TTreeReader.h>
#include <StRPEvent.h>
#include <StUPCRpsTrack.h>
#include <StUPCRpsTrackPoint.h>
#include <StUPCEvent.h>
#include <StUPCTrack.h>
#include <StUPCBemcCluster.h>
#include <StUPCVertex.h>
#include <StUPCTofHit.h>
#include "MatchFillPosition.h"
#include "ReadFillPositionFile.h"
#include "StUPCV0.h"
//#include "ReadPicoLambdaK0.h"
# endif // INCLUDES_H
